name: courier_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  # Firebase core & Firestore
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # HTTP requests
  http: ^1.2.2

  # Manejo de enlaces profundos (sustituye a uni_links)
  app_links: ^3.5.0

  # Formato de hora
  intl: ^0.20.2

  # Íconos de iOS
  cupertino_icons: ^1.0.8

  # Acceso a cámara / galería
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Buenas prácticas de código
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
